genall: Test\ Cases\ TADs\ -\ tests.csv
	python3 gen_tests_txt.py eval Test\ Cases\ TADs\ -\ tests.csv > casos_eval.txt
	python3 gen_tests_txt.py noparse Test\ Cases\ TADs\ -\ tests.csv > casos_noparse.txt
	python3 gen_tests_txt.py parse Test\ Cases\ TADs\ -\ tests.csv > casos_parse.txt
	python3 gen_tests_txt.py igobs Test\ Cases\ TADs\ -\ tests.csv > casos_igobs.txt
	python3 gen_tests_txt.py noigobs Test\ Cases\ TADs\ -\ tests.csv > casos_noigobs.txt

.PHONY: genall
