name: CI

on: [push, pull_request]
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: npm i
        
      - name: Run tests
        run: npm run test
        
      - name: Build site
        run: npm run build
        
      - name: Deploy site to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          # uso la ruta completa porque el cli esta medio loco
          args: deploy --dir=/home/runner/work/tads/tads/build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
 

