name: CI

on: [push]
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: npm i
        
      - name: Run tests
        run: npm run test
        
      - name: Build site
        run: npm run build
        
      - name: Deploy site to Netlify
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
